### ISSUE TITLE
hard coded paths to data files

### ISSUE THREAD

**Issue by ArtPoon** [ArtPoon/sc2rf#1]
prevents user from calling main script from outside project directory
```console
art@Wernstrom git % python3 sc2rf/sc2rf.py
Traceback (most recent call last):
  File "/Users/art/git/sc2rf/sc2rf.py", line 987, in <module>
    main()
  File "/Users/art/git/sc2rf/sc2rf.py", line 73, in main
    mappings = read_mappings('mapping.csv')
  File "/Users/art/git/sc2rf/sc2rf.py", line 875, in read_mappings
    with open(path, newline='') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'mapping.csv'
```

**Comment by lenaschimmel** [comment]
I'm currently working on this as part of [lenaschimmel#3](https://github.com/lenaschimmel/sc2rf/issues/3) in the [resources](https://github.com/lenaschimmel/sc2rf/tree/resources) branch.

It's mostly working, but since `virus_properties.json` is both a resource that's bundled with the program, and something the program can update itself, I still need to put it into a writable location. As soon as I fix this, I will merge that branch.
